#!/bin/bash

PARAMETERS_FILE=
PASSWORD=no

# Parse command line options.
for i in "$@"; do
    case $i in
        -f:*|--parameters-file:*)
            PARAMETERS_FILE="${i#*:}"
            ;;
        -p:*|--password:*)
            PASSWORD="${i#*:}"
            ;;
    esac
done

if [ "$PARAMETERS_FILE" == "" ]; then
    echo "usage: $0 -f:'parameters file' [-p:[yes | no]]"
    exit 1
fi

PRIVATE_KEY=ec_private_key.pem
PUBLIC_KEY=ec_public_key.pem

if [ -e "$PRIVATE_KEY" ]; then
    echo "Deleting old private key."
    rm "$PRIVATE_KEY"
fi
echo "Generating new private key."
if [ "$PASSWORD" == "yes" ]; then
    openssl genpkey -aes256 -paramfile "$PARAMETERS_FILE" -out "$PRIVATE_KEY"
else
    openssl genpkey -paramfile "$PARAMETERS_FILE" -out "$PRIVATE_KEY"
fi

if [ -e "$PUBLIC_KEY" ]; then
    echo "Deleting old public key."
    rm "$PUBLIC_KEY"
fi
echo "Extracting new public key."
openssl ec -in "$PRIVATE_KEY" -pubout -out "$PUBLIC_KEY"

exit 0
