#!/bin/bash

BITS=4096
PASSWORD=no

# Parse command line options.
for i in "$@"; do
    case $i in
        -b:*|--bits:*)
            BITS="${i#*:}"
            ;;
        -p:*|--password:*)
            PASSWORD="${i#*:}"
            ;;
    esac
done

if [ "$BITS" == "" ]; then
    echo "usage: $0 [-b:'bits'] [-p:[yes | no]]"
    exit 1
fi

PRIVATE_KEY=rsa_private_key.pem
PUBLIC_KEY=rsa_public_key.pem

if [ -e "$PRIVATE_KEY" ]; then
    echo "Deleting old private key."
    rm "$PRIVATE_KEY"
fi
echo "Generating new private key."
if [ "$PASSWORD" == "yes" ]; then
    openssl genrsa -aes256 -out "$PRIVATE_KEY" "$BITS"
else
    openssl genrsa -out "$PRIVATE_KEY" "$BITS"
fi

if [ -e "$PUBLIC_KEY" ]; then
    echo "Deleting old public key."
    rm "$PUBLIC_KEY"
fi
echo "Extracting new public key."
openssl rsa -pubout -in "$PRIVATE_KEY" -out "$PUBLIC_KEY"

exit 0
